apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-volume-claim
spec:
  storageClassName: storage-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
