apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ .Values.alertmanager.name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.alertmanager.name }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{.Values.alertmanager.name }}
data:
#{{ toYaml .Values.alertmanagerFiles | indent 2 }}
  alertmanager.yml: |-
    global:
    resolve_timeout: 1m
   
    route:
    receiver: 'gmail-notifications'
   
    receivers:
      - name: 'gmail-notifications'
    email_configs:
    - to: msr2858@gmail.com
      from: msr2858@gmail.com
      smarthost: smtp.gmail.com:587
      auth_username: msr2858@gmail.com
      auth_identity: msr2858@gmail.com
      auth_password: password
      send_resolved: true