{{- if .Values.alertmanager.persistentVolume.enabled -}}

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.alertmanager.name }}
  namespace: monitoring
  labels:
    name: alertmanager-pv-claim
spec:
  storageClassName: {{ .Values.alertmanager.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi