apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ .Values.alertmanager.name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.alertmanager.name }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{.Values.alertmanager.name }}
data:
{{ toYaml .Values.alertmanagerFiles | indent 2 }}