apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.server.name }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ .Values.server.name }}-config
data:
{{ toYaml .Values.serverConfigFile | indent 2 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: grafana
  name: {{ .Values.server.name }}-dashs
  namespace: monitoring
data:
  prometheus.yml: |-
    {
        "apiVersion": 1,
        "datasources": [
            {
               "access":"proxy",
                "editable": true,
                "name": "prometheus-data",
                "orgId": 1,
                "type": "prometheus",
                "url": "http://prometheus-mon.monitoring.svc:9090",
                "version": 1
            }
        ]
    }