kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.server.name }}-config
  namespace: monitoring
  labels:
    name: grafana-pv-claim
spec:
  storageClassName: grafana-storage-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi