apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.server.name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.server.name }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ .Values.server.name }}
spec:
  ports:
    - name: {{ default "http" .Values.server.httpPortName | quote }}
      port: {{ .Values.server.httpPort }}
      protocol: TCP
      targetPort: 3000
  selector:
    app: {{ .Values.server.name }}
    component: "{{ .Values.server.name }}"
  type: "{{ .Values.server.serviceType }}"
