apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.server.name }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ .Values.server.name }}-config
data:
{{ toYaml .Values.serverConfigFile | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.server.name }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ .Values.server.name }}-dashs
data:
{{ toYaml .Values.serverDashboardFiles | indent 2 }}