apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ .Values.server.name }}-secret
type: Opaque
data:
  
  grafana-admin-password:  {{ .Values.server.adminPassword | b64enc | quote }}
  grafana-admin-user: {{ .Values.server.adminUser | b64enc | quote }}