apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.server.name }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{ .Values.server.name }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ .Values.server.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.server.name }}
  template:
    metadata:
      annotations:
      {{- range $key, $value := .Values.server.annotations }}
        {{ $key }}: {{ $value }}
      {{- end }}
      labels:
        app: {{ .Values.server.name }}
        component: "{{ .Values.server.name }}"
        release: "{{ .Release.Name }}"
    spec:
      containers:
        - name: {{ .Values.server.name }}
          image: "{{ .Values.server.image }}"
          imagePullPolicy: {{ default "Always" .Values.server.imagePullPolicy }}
          env:
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.server.name }}-secret
                  key: grafana-admin-user
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.server.name }}-secret
                  key: grafana-admin-password
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /login
              port: 3000
            initialDelaySeconds: 30
            timeoutSeconds: 30
          resources:
{{ toYaml .Values.server.resources | indent 12 }}
          volumeMounts:
            - name: grafana-storage
              mountPath: {{ default "/var/lib/grafana" .Values.server.configLocalPath | quote }}
            - name: grafana-datasources
              mountPath: {{ default "/etc/grafana/provisioning/datasources" .Values.server.storageLocalPath | quote }}
              readOnly: false
      volumes:
        - name: grafana-storage
          configMap:
            name: {{ .Values.server.name }}-config
            defaultMode: 420
        - name: grafana-datasources
          configMap:
            name: {{ .Values.server.name }}-dashs
            defaultMode: 420
        - name: grafana-pvc
          persistentVolumeClaim:
            claimName: {{ .Values.server.name }}-config
    