apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.kubeStateMetrics.name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.kubeStateMetrics.name }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ .Values.kubeStateMetrics.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.kubeStateMetrics.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.kubeStateMetrics.name }}
        component: "{{ .Values.kubeStateMetrics.name }}"
        release: "{{ .Release.Name }}"
    spec:
      containers:
        - name: {{ .Values.kubeStateMetrics.name }}-{{ .Values.kubeStateMetrics.name }}
          image: "{{ .Values.kubeStateMetrics.image }}"
          imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
          ports:
            - containerPort: 8080
          resources:
{{ toYaml .Values.alertmanager.resources | indent 12 }}