apiVersion: v1
kind: Service
metadata: 
  annotations: 
    prometheus.io/scrape: "true"
 #   cloud.google.com/load-balancer-type: "Internal"
  name: prometheus-mon
  namespace: monitoring
spec:
  selector:
    app: prometheus-server
  type: LoadBalancer
  ports:
  - name: prometheus
    protocol: TCP
    port: 9090
    nodePort: 31473
    targetPort: 9090